<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SaranaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nama' => 'Proyektor',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Rapat',
                'status' => 'baik',
                'jumlah' => 5,
                'deskripsi' => 'Proyektor untuk presentasi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Kursi Lipat',
                'kategori' => 'Furniture',
                'lokasi' => 'Aula',
                'status' => 'baik',
                'jumlah' => 50,
                'deskripsi' => 'Kursi lipat untuk acara',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Laptop',
                'kategori' => 'Elektronik',
                'lokasi' => 'Lab Komputer',
                'status' => 'pemeliharaan',
                'jumlah' => 10,
                'deskripsi' => 'Laptop untuk pelatihan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Meja Belajar',
                'kategori' => 'Furniture',
                'lokasi' => 'Ruang Kelas',
                'status' => 'baik',
                'jumlah' => 30,
                'deskripsi' => 'Meja belajar untuk siswa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'AC',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Guru',
                'status' => 'baik',
                'jumlah' => 3,
                'deskripsi' => 'AC untuk pendingin ruangan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Whiteboard',
                'kategori' => 'Peralatan',
                'lokasi' => 'Ruang Kelas',
                'status' => 'baik',
                'jumlah' => 10,
                'deskripsi' => 'Whiteboard untuk menulis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Printer',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Administrasi',
                'status' => 'baik',
                'jumlah' => 2,
                'deskripsi' => 'Printer untuk mencetak dokumen',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Rak Buku',
                'kategori' => 'Furniture',
                'lokasi' => 'Perpustakaan',
                'status' => 'baik',
                'jumlah' => 15,
                'deskripsi' => 'Rak buku untuk menyimpan koleksi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Speaker',
                'kategori' => 'Elektronik',
                'lokasi' => 'Aula',
                'status' => 'baik',
                'jumlah' => 4,
                'deskripsi' => 'Speaker untuk acara',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Mikrofon',
                'kategori' => 'Elektronik',
                'lokasi' => 'Aula',
                'status' => 'baik',
                'jumlah' => 6,
                'deskripsi' => 'Mikrofon untuk presentasi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Komputer',
                'kategori' => 'Elektronik',
                'lokasi' => 'Lab Komputer',
                'status' => 'baik',
                'jumlah' => 20,
                'deskripsi' => 'Komputer untuk pembelajaran',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Papan Tulis',
                'kategori' => 'Peralatan',
                'lokasi' => 'Ruang Kelas',
                'status' => 'baik',
                'jumlah' => 10,
                'deskripsi' => 'Papan tulis untuk menulis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Kipas Angin',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Kelas',
                'status' => 'baik',
                'jumlah' => 8,
                'deskripsi' => 'Kipas angin untuk ventilasi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Televisi',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Tunggu',
                'status' => 'baik',
                'jumlah' => 2,
                'deskripsi' => 'Televisi untuk hiburan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Alat Kebersihan',
                'kategori' => 'Peralatan',
                'lokasi' => 'Gudang',
                'status' => 'baik',
                'jumlah' => 10,
                'deskripsi' => 'Alat kebersihan untuk membersihkan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Meja Rapat',
                'kategori' => 'Furniture',
                'lokasi' => 'Ruang Rapat',
                'status' => 'baik',
                'jumlah' => 1,
                'deskripsi' => 'Meja untuk rapat',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'CCTV',
                'kategori' => 'Elektronik',
                'lokasi' => 'Kantor',
                'status' => 'baik',
                'jumlah' => 5,
                'deskripsi' => 'CCTV untuk keamanan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Alat Tulis',
                'kategori' => 'Peralatan',
                'lokasi' => 'Ruang Guru',
                'status' => 'baik',
                'jumlah' => 100,
                'deskripsi' => 'Alat tulis untuk kebutuhan kantor',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Dispenser',
                'kategori' => 'Elektronik',
                'lokasi' => 'Ruang Guru',
                'status' => 'baik',
                'jumlah' => 3,
                'deskripsi' => 'Dispenser untuk air minum',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'Jam Dinding',
                'kategori' => 'Peralatan',
                'lokasi' => 'Ruang Kelas',
                'status' => 'baik',
                'jumlah' => 10,
                'deskripsi' => 'Jam dinding untuk penunjuk waktu',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert data into the sarana table
        $this->db->table('sarana')->insertBatch($data);
    }
}
